/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as ShopRouteImport } from './routes/shop'
import { Route as ContactRouteImport } from './routes/contact'
import { Route as CartRouteImport } from './routes/cart'
import { Route as AboutRouteImport } from './routes/about'
import { Route as IndexRouteImport } from './routes/index'
import { Route as Admin_talianiIndexRouteImport } from './routes/admin_taliani.index'
import { Route as ProductSlugRouteImport } from './routes/product.$slug'
import { Route as Admin_talianiDashboardRouteImport } from './routes/admin_taliani.dashboard'

const ShopRoute = ShopRouteImport.update({
  id: '/shop',
  path: '/shop',
  getParentRoute: () => rootRouteImport,
} as any)
const ContactRoute = ContactRouteImport.update({
  id: '/contact',
  path: '/contact',
  getParentRoute: () => rootRouteImport,
} as any)
const CartRoute = CartRouteImport.update({
  id: '/cart',
  path: '/cart',
  getParentRoute: () => rootRouteImport,
} as any)
const AboutRoute = AboutRouteImport.update({
  id: '/about',
  path: '/about',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const Admin_talianiIndexRoute = Admin_talianiIndexRouteImport.update({
  id: '/admin_taliani/',
  path: '/admin_taliani/',
  getParentRoute: () => rootRouteImport,
} as any)
const ProductSlugRoute = ProductSlugRouteImport.update({
  id: '/product/$slug',
  path: '/product/$slug',
  getParentRoute: () => rootRouteImport,
} as any)
const Admin_talianiDashboardRoute = Admin_talianiDashboardRouteImport.update({
  id: '/admin_taliani/dashboard',
  path: '/admin_taliani/dashboard',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/cart': typeof CartRoute
  '/contact': typeof ContactRoute
  '/shop': typeof ShopRoute
  '/admin_taliani/dashboard': typeof Admin_talianiDashboardRoute
  '/product/$slug': typeof ProductSlugRoute
  '/admin_taliani/': typeof Admin_talianiIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/cart': typeof CartRoute
  '/contact': typeof ContactRoute
  '/shop': typeof ShopRoute
  '/admin_taliani/dashboard': typeof Admin_talianiDashboardRoute
  '/product/$slug': typeof ProductSlugRoute
  '/admin_taliani': typeof Admin_talianiIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/cart': typeof CartRoute
  '/contact': typeof ContactRoute
  '/shop': typeof ShopRoute
  '/admin_taliani/dashboard': typeof Admin_talianiDashboardRoute
  '/product/$slug': typeof ProductSlugRoute
  '/admin_taliani/': typeof Admin_talianiIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/about'
    | '/cart'
    | '/contact'
    | '/shop'
    | '/admin_taliani/dashboard'
    | '/product/$slug'
    | '/admin_taliani/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/about'
    | '/cart'
    | '/contact'
    | '/shop'
    | '/admin_taliani/dashboard'
    | '/product/$slug'
    | '/admin_taliani'
  id:
    | '__root__'
    | '/'
    | '/about'
    | '/cart'
    | '/contact'
    | '/shop'
    | '/admin_taliani/dashboard'
    | '/product/$slug'
    | '/admin_taliani/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AboutRoute: typeof AboutRoute
  CartRoute: typeof CartRoute
  ContactRoute: typeof ContactRoute
  ShopRoute: typeof ShopRoute
  Admin_talianiDashboardRoute: typeof Admin_talianiDashboardRoute
  ProductSlugRoute: typeof ProductSlugRoute
  Admin_talianiIndexRoute: typeof Admin_talianiIndexRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/shop': {
      id: '/shop'
      path: '/shop'
      fullPath: '/shop'
      preLoaderRoute: typeof ShopRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/contact': {
      id: '/contact'
      path: '/contact'
      fullPath: '/contact'
      preLoaderRoute: typeof ContactRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/cart': {
      id: '/cart'
      path: '/cart'
      fullPath: '/cart'
      preLoaderRoute: typeof CartRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/about': {
      id: '/about'
      path: '/about'
      fullPath: '/about'
      preLoaderRoute: typeof AboutRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin_taliani/': {
      id: '/admin_taliani/'
      path: '/admin_taliani'
      fullPath: '/admin_taliani/'
      preLoaderRoute: typeof Admin_talianiIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/product/$slug': {
      id: '/product/$slug'
      path: '/product/$slug'
      fullPath: '/product/$slug'
      preLoaderRoute: typeof ProductSlugRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin_taliani/dashboard': {
      id: '/admin_taliani/dashboard'
      path: '/admin_taliani/dashboard'
      fullPath: '/admin_taliani/dashboard'
      preLoaderRoute: typeof Admin_talianiDashboardRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AboutRoute: AboutRoute,
  CartRoute: CartRoute,
  ContactRoute: ContactRoute,
  ShopRoute: ShopRoute,
  Admin_talianiDashboardRoute: Admin_talianiDashboardRoute,
  ProductSlugRoute: ProductSlugRoute,
  Admin_talianiIndexRoute: Admin_talianiIndexRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { createStart } from '@tanstack/react-start'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
  }
}
